using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DotnetEcommerceStore.Models;

namespace DotnetEcommerceStore.Data
{
    public class EComerceDbContext : DbContext
    {
        public EComerceDbContext(DbContextOptions<EComerceDbContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>().HasData(
                new Product
                {
                    ID = 1,
                    SKU = "12",
                    Name = "Violin",
                    Description = "A stringed instrument that emits pleasant tones. Can be played solo or in an orchestra",
                    Price = 350,
                },
                new Product
                {
                    ID = 2,
                    SKU = "123",
                    Name = "Hurdy Gurdy",
                    Description = "Pear-shaped fiddle having strings that are sounded not by a bow but by the rosined rim of a wooden wheel turned by a handle at the instrument's end.",
                    Price = 9000,
                },
                new Product
                {
                    ID = 3,
                    SKU = "1234",
                    Name = "Kazoo",
                    Description = " instrument that adds a buzzing timbral quality to a player's voice when the player vocalizes into it",
                    Price = 100,
                },
                new Product
                {
                    ID = 4,
                    SKU = "12345",
                    Name = "Didgeridoo",
                    Description = " Australian Aboriginal wind instrument, which is blown to produce a deep, resonant sound, varied by rhythmic accents of timbre and volume.",
                    Price = 27,
                },
                new Product
                {
                    ID = 5,
                    SKU = "123456",
                    Name = "Lute",
                    Description = "Waisted resonating chamber with goatskin belly. Carved wooden makara finial. Gut strings. Played with small, attached plectrum.",
                    Price = 568,
                },
                new Product
                {
                    ID = 6,
                    SKU = "1234567",
                    Name = "Theremin",
                    Description = "electronic musical instrument in which the tone is generated by two high-frequency oscillators and the pitch controlled by the movement of the performer's hand toward and away from the circuit.",
                    Price = 123,
                },
                new Product
                {
                    ID = 7,
                    SKU = "12345678",
                    Name = "Tenor saxophone",
                    Description = "Single reed saxophone made of brass and a tapered bore on a fingering system based on that of the oboe",
                    Price = 789,
                },
                new Product
                {
                    ID = 8,
                    SKU = "123456789",
                    Name = "Hydrolauphone",
                    Description = "instruments produce sound hydraulically, as music is played by covering different water jets to produce different pitches",
                    Price = 1999,
                },
                new Product
                {
                    ID = 9,
                    SKU = "987654",
                    Name = "Glass Harmonica",
                    Description = "A series of glass bowls rotates while the player simply touches the bowls with wet fingers to create the desired notes",
                    Price = 894,
                },
                new Product
                {
                    ID = 10,
                    SKU = "987654321",
                    Name = "Pyrophone",
                    Description = "An organ that is powered by gasoline and propane; he sound are produced by combustion and explosion.",
                    Price = 25,
                });
        }

        public DbSet<Product> Products { get; set; }

        public DbSet<CartItems> CartItems { get; set; }

        public DbSet<Cart> Cart { get; set; }

        public DbSet<Checkout> Checkout { get; set; }

        public DbSet<CheckoutItems> CheckoutItems { get; set; }
    }
}
